kind: pipeline
type: docker
name: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: ??
      username: ??
      password: ??
      repo: tzrlk/valheim
      context: src/docker