version: '3.2'

services:
  
  valheim:
    container_name: valheim
    image: tzrlk/valheim-server
    build:
      context: .
    cap_add:
      - SYS_NICE
    volumes:
      - ./config:/config
      - ./data:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp" # valheim
      - "9001:9001/tcp" # admin
      - "80:80/tcp" # status
    environment:
      SERVER_NAME:     'Bunnings'
      SERVER_PORT:     '2456'
      WORLD_NAME:      'Bunnings'
      UPDATE_CRON:     '@reboot' # TODO: Should be disabled in new build.
      BACKUPS_IF_IDLE: 'false'
    restart:           always
    stop_grace_period: 2m
    
  dnsupdater:
    container_name: dnsupdater
    image: vagalume/route53-updater:latest
    environment:
      AWS_ROUTE53_ZONEID:    aetheric.co.nz
      AWS_ROUTE53_HOST:      valheim.aetheric.co.nz
      AWS_ROUTE53_TTL:       3600
      